name: gather
description: A community weather data gathering application built on flutter
version: 0.0.1+1
environment: 
  sdk: '>=2.17.0 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  flutter_lints: ^3.0.1
  provider: ^6.0.4
  cached_network_image: ^3.2.1
  flutter_svg: ^2.0.9
  connectivity_plus: ^6.0.1
  shared_preferences: ^2.0.15
  intl: ^0.18.0
  maplibre_gl:
    git:
      url: https://github.com/maplibre/flutter-maplibre-gl.git
      ref: main
      publish_to: none
  font_awesome_flutter:  ^10.1.0
  google_fonts: ^4.0.3
  badges: ^3.1.2
  flutterflow_ui: ^0.2.0
  supabase_auth_ui: ^0.3.0
  image_picker: ^1.0.7
  flutter_speed_dial: ^7.0.0
  intl_phone_number_input: ^0.7.0+2


dev_dependencies: 
  flutter_test: 
    sdk: flutter
  test: ^1.24.9
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Roboto
      fonts: 
        - asset: assets/fonts/RobotoRegular.ttf
          weight: 400
