name: Run GAs on Standard Github Hosted Runner

on:
  push:
    branches: [main, testing]
  pull_request:
    branches: [main, testing]
    
jobs:
  build:
    runs-on: ubuntu-latest
    name: Run GAs on Linux Runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: 'testing'
    
      - name: Code Coverage Summary
        id: coverage
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage/**/cobertura.xml
          output: both
          badge: true
          format: markdown
          hide_complexity: true

      - name: Update README.md with Coverage Badge
        run: |
          # Extract the URL using a regex
          # url=$(echo "${{ steps.coverage.outputs.stdout }}" | grep -oP '(?<=\!\[Code Coverage\]\().*?(?=\))')
          # Output the extracted URL
          echo "{{ steps.coverage.outputs.* }}"
      #     # Define the badge URL (adjust the URL according to your badge)
      #     BADGE_URL="${{ steps.coverage.output }}"
      #     # Update README.md
      #     echo "![Test Coverage]($BADGE_URL)" >> README.md

      # - name: Commit and Push Changes
      #   run: |
      #     git config --local user.email "action@github.com"
      #     git config --local user.name "GitHub Action"
      #     git add README.md
      #     git commit -m "Update README.md with coverage badge"
      #     git push
      #   env:  
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            

      
